networks:
  isard_network:
    external: false
    name: isard_network
  stonith:
    driver: macvlan
    driver_opts:
      parent: drbd
    ipam:
      config:
      - subnet: 172.31.3.0/24
services:
  isard-app:
    build:
      context: /opt/isard/devel-isard
      dockerfile: dockers/app/Dockerfile
      target: development
    container_name: isard-app
    depends_on:
    - isard-database
    extra_hosts:
      isard-engine: 127.0.0.1
    image: isard/app:1.2.2-beta
    networks:
      isard_network: {}
    ports:
    - published: 5000
      target: 5000
    - published: 5555
      target: 5555
    restart: "no"
    volumes:
    - /opt/isard/certs:/certs:rw
    - /etc/localtime:/etc/localtime:ro
    - /opt/isard/devel-isard/src:/isard:rw
    - /opt/isard/backups:/isard/backups:rw
    - /opt/isard/database/wizard:/isard/install/wizard:rw
    - /opt/isard/logs:/isard/logs:rw
    - /opt/isard/uploads:/isard/uploads:rw
    - /opt/isard/sshkeys:/root/.ssh:rw
  isard-database:
    container_name: isard-database
    image: rethinkdb
    networks:
      isard_network: {}
    ports:
    - published: 8080
      target: 8080
    - published: 28015
      target: 28015
    restart: "no"
    volumes:
    - /opt/isard/database:/data:rw
    - /etc/localtime:/etc/localtime:ro
  isard-grafana:
    build:
      context: /opt/isard/devel-isard
      dockerfile: extras/grafana/Dockerfile
    container_name: isard-grafana
    environment:
      GRAFANA_DOMAIN: demo.isardvdi.com
    image: isard/grafana:1.1
    logging:
      driver: none
    networks:
      isard_network: {}
    ports:
    - mode: host
      protocol: tcp
      published: 3000
      target: 3000
    restart: "no"
    volumes:
    - /opt/isard/grafana/grafana/data:/grafana/data:rw
    - /opt/isard/grafana/graphite/conf:/opt/graphite/conf:rw
    - /opt/isard/grafana/graphite/storage:/opt/graphite/storage:rw
  isard-mosquitto:
    build:
      context: /opt/isard/devel-isard
      dockerfile: extras/mosquitto/Dockerfile
    container_name: isard-mosquitto
    image: isard/mosquitto:0.1
    networks:
      isard_network: {}
      stonith:
        ipv4_address: 172.31.3.10
    ports:
    - mode: host
      protocol: tcp
      published: 1883
      target: 1883
    restart: "no"
    volumes:
    - /opt/isard/devel-isard/extras/mosquitto/mqtt-carbon-proxy.py:/mqtt-carbon-proxy.py:rw
    - /opt/isard/logs/mosquitto:/var/log:rw
  isard-nginx:
    build:
      context: /opt/isard/devel-isard
      dockerfile: dockers/nginx/Dockerfile
      target: development
    container_name: isard-nginx
    depends_on:
    - isard-app
    image: isard/nginx:1.2.2-beta
    networks:
      isard_network: {}
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    restart: "no"
    volumes:
    - /opt/isard/devel-isard/dockers/hypervisor/add-hyper-rethink.py:/add-hyper-rethink.py:rw
    - /opt/isard/devel-isard/dockers/hypervisor/add-hypervisor.sh:/add-hypervisor.sh:rw
    - /opt/isard/devel-isard/dockers/nginx/dh.pem:/dh.pem:rw
    - /opt/isard/devel-isard/dockers/nginx/errors:/errors:rw
    - /etc/localtime:/etc/localtime:ro
    - /opt/isard/certs/default:/etc/nginx/external:rw
    - /opt/isard/devel-isard/dockers/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    - /opt/isard/devel-isard/dockers/nginx/auto-generate-certs.sh:/opt/auto-generate-certs.sh:rw
    - /opt/isard/logs/nginx:/var/log/nginx:rw
    - /opt/isard/devel-isard/src/webapp/static/viewers:/viewers:rw
version: '3.5'

