version: "3.5"
services:
  isard-database:
    container_name: isard-database
    volumes:
      - "/opt/isard/database:/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - isard_network
    image: rethinkdb
    restart: unless-stopped

  isard-nginx:
    container_name: isard-nginx
    volumes:
      - "/opt/isard/certs/default:/etc/nginx/external"
      - "/opt/isard/logs/nginx:/var/log/nginx"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - isard_network
    image: isard/nginx:${TAG:-latest}
    build:
      context: /opt/isard/devel-isard
      dockerfile: dockers/nginx/Dockerfile    
    restart: unless-stopped
    depends_on:
      - isard-app

  isard-app:
    container_name: isard-app
    volumes:
      - "/opt/isard/sshkeys:/root/.ssh"
      - "/opt/isard/certs:/certs"
      - "/opt/isard/logs:/isard/logs"
      - "/opt/isard/database/wizard:/isard/install/wizard"
      - "/opt/isard/backups:/isard/backups"
      - "/opt/isard/uploads:/isard/uploads"
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "isard-engine:127.0.0.1"
    networks:
      - isard_network
    image: isard/app:${TAG:-latest}
    build:
      context: /opt/isard/devel-isard
      dockerfile: dockers/app/Dockerfile
      target: production
    restart: unless-stopped
    depends_on:
      - isard-database

  isard-grafana:
    container_name: isard-grafana
    volumes:
      - "/opt/isard/grafana/grafana/data:/grafana/data"
      - "/opt/isard/grafana/graphite/storage:/opt/graphite/storage"
      - "/opt/isard/grafana/graphite/conf:/opt/graphite/conf"
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - isard_network
    image: isard/grafana:1.1
    build:
      context: /opt/isard/devel-isard
      dockerfile: extras/grafana/Dockerfile    
    restart: "no"
    logging:
        driver: none
    env_file:
      - config.env
  isard-mosquitto:
    container_name: isard-mosquitto
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    volumes:
      - "/opt/isard/logs/mosquitto:/var/log/"
    networks:
      isard_network: null
      stonith:
        ipv4_address: 172.31.3.10
    image: isard/mosquitto:0.1
    build:
      context: /opt/isard/devel-isard
      dockerfile: extras/mosquitto/Dockerfile    
    restart: "no"

networks:
  isard_network:
    external: false
    name: isard_network
  stonith:
    driver: macvlan
    driver_opts:
      parent: drbd
    ipam:
      config:
        - subnet: 172.31.3.0/24

