version: "3.5"
services:
  isard-hypervisor:
    container_name: isard-hypervisor
    volumes:
      - "/opt/isard/ssh-certs/$HOSTNAME:/root/.ssh"
      - "/opt/isard:/isard"
      - "/opt/isard/certs/default:/etc/pki/libvirt-spice"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "2022:22"
      - "5900-5999:5900-5999"
      - "55900-55999:55900-55999"
    image: isard/hypervisor:1.2.1
    build:
      context: .
      dockerfile: dockers/hypervisor/Dockerfile    
    privileged: true
    restart: "no"
