version: "3.5"
services:
  isard-database:
    container_name: isard-database
    volumes:
      - "/opt/isard/database:/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - isard_network
    image: rethinkdb
    restart: "no"

  isard-nginx:
    container_name: isard-nginx
    volumes:
      - "/opt/isard/certs/default:/etc/nginx/external"
      - "/opt/isard/logs/nginx:/var/log/nginx"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - isard_network
    image: isard/nginx:${TAG:-latest}
    build:
      context: .
      dockerfile: dockers/nginx/Dockerfile    
    restart: "no"
    depends_on:
      - isard-app

  isard-hypervisor:
    container_name: isard-hypervisor
    volumes:
      - "/opt/isard/ssh-certs:/root/.ssh"
      - "/opt/isard:/isard"
      - "/opt/isard/certs/default:/etc/pki/libvirt-spice"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5900-5999:5900-5999"
      - "55900-55999:55900-55999"
    networks:
      - isard_network
    image: isard/hypervisor:${TAG:-latest}
    build:
      context: .
      dockerfile: dockers/hypervisor/Dockerfile    
    privileged: true
    restart: "no"
        
  isard-app:
    container_name: isard-app
    volumes:
      - "/opt/isard/ssh-certs:/root/.ssh"
      - "/opt/isard/certs:/certs"
      - "/opt/isard/logs:/isard/logs"
      - "/opt/isard/database/wizard:/isard/install/wizard"
      - "/opt/isard/backups:/isard/backups"
      - "/opt/isard/uploads:/isard/uploads"
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "isard-engine:127.0.0.1"
    networks:
      - isard_network
    image: isard/app:${TAG:-latest}
    build:
      context: .
      dockerfile: dockers/app/Dockerfile
      target: production
    restart: "no"
    depends_on:
      - isard-database
      - isard-hypervisor

  isard-grafana:
    container_name: isard-grafana
    volumes:
      - "/opt/isard/grafana/grafana/data:/grafana/data"
      - "/opt/isard/grafana/graphite/storage:/opt/graphite/storage"
      - "/opt/isard/grafana/graphite/conf:/opt/graphite/conf"
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - isard_network
    image: isard/grafana:1.1
    restart: "no"
    logging:
        driver: none
    #~ depends_on:
      #~ - isard-app

  isard-mosquitto:
    container_name: isard-mosquitto
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    networks:
      - isard_network
    image: isard/mosquitto:0.1
    restart: "no"


networks:
  isard_network:
    external: false
    name: isard_network
